package default_package;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-12-27T21:28:27.972Z
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://default_package/", name = "ServerSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServerSoap {

    @WebMethod
    @RequestWrapper(localName = "reservarQuarto", targetNamespace = "http://default_package/", className = "default_package.ReservarQuarto")
    @ResponseWrapper(localName = "reservarQuartoResponse", targetNamespace = "http://default_package/", className = "default_package.ReservarQuartoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean reservarQuarto(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebMethod
    @RequestWrapper(localName = "autenticarUser", targetNamespace = "http://default_package/", className = "default_package.AutenticarUser")
    @ResponseWrapper(localName = "autenticarUserResponse", targetNamespace = "http://default_package/", className = "default_package.AutenticarUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String autenticarUser(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "cancelarQuarto", targetNamespace = "http://default_package/", className = "default_package.CancelarQuarto")
    @ResponseWrapper(localName = "cancelarQuartoResponse", targetNamespace = "http://default_package/", className = "default_package.CancelarQuartoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean cancelarQuarto(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "listarQuartos", targetNamespace = "http://default_package/", className = "default_package.ListarQuartos")
    @ResponseWrapper(localName = "listarQuartosResponse", targetNamespace = "http://default_package/", className = "default_package.ListarQuartosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Integer> listarQuartos(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "registarUser", targetNamespace = "http://default_package/", className = "default_package.RegistarUser")
    @ResponseWrapper(localName = "registarUserResponse", targetNamespace = "http://default_package/", className = "default_package.RegistarUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String registarUser(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
