package default_package;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-12-27T21:28:27.981Z
 * Generated source version: 3.4.5
 *
 */
@WebServiceClient(name = "ServerSoapService",
                  wsdlLocation = "http://localhost:8080/ServerSoap/services/ServerSoapPort?wsdl",
                  targetNamespace = "http://default_package/")
public class ServerSoapService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://default_package/", "ServerSoapService");
    public final static QName ServerSoapPort = new QName("http://default_package/", "ServerSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ServerSoap/services/ServerSoapPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServerSoapService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ServerSoap/services/ServerSoapPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServerSoapService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServerSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerSoapService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServerSoapService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServerSoapService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServerSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ServerSoap
     */
    @WebEndpoint(name = "ServerSoapPort")
    public ServerSoap getServerSoapPort() {
        return super.getPort(ServerSoapPort, ServerSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerSoap
     */
    @WebEndpoint(name = "ServerSoapPort")
    public ServerSoap getServerSoapPort(WebServiceFeature... features) {
        return super.getPort(ServerSoapPort, ServerSoap.class, features);
    }

}
