
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package default_package;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-12-27T21:28:27.955Z
 * Generated source version: 3.4.5
 *
 */

@javax.jws.WebService(
                      serviceName = "ServerSoapService",
                      portName = "ServerSoapPort",
                      targetNamespace = "http://default_package/",
                      wsdlLocation = "http://localhost:8080/ServerSoap/services/ServerSoapPort?wsdl",
                      endpointInterface = "default_package.ServerSoap")

public class ServerSoapPortImpl implements ServerSoap {

    private static final Logger LOG = Logger.getLogger(ServerSoapPortImpl.class.getName());

    /* (non-Javadoc)
     * @see default_package.ServerSoap#reservarQuarto(int arg0, int arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4)*
     */
    public java.lang.Boolean reservarQuarto(int arg0, int arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4) {
        LOG.info("Executing operation reservarQuarto");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        try {
            java.lang.Boolean _return = Boolean.valueOf(false);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.ServerSoap#autenticarUser(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String autenticarUser(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation autenticarUser");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-1826538930";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.ServerSoap#cancelarQuarto(int arg0, java.lang.String arg1, java.lang.String arg2)*
     */
    public java.lang.Boolean cancelarQuarto(int arg0, java.lang.String arg1, java.lang.String arg2) {
        LOG.info("Executing operation cancelarQuarto");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            java.lang.Boolean _return = Boolean.valueOf(false);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.ServerSoap#listarQuartos(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.util.List<java.lang.Integer> listarQuartos(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation listarQuartos");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.util.List<java.lang.Integer> _return = new java.util.ArrayList<java.lang.Integer>();
            java.lang.Integer _returnVal1 = Integer.valueOf(230980347);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.ServerSoap#registarUser(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String registarUser(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation registarUser");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-1238255635";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
